
development:
  adapter: postgresql
  encoding: unicode
  database: MinexReports_development
  pool: 5
  username: dj
  password: jordan

test:
  adapter: postgresql
  encoding: unicode
  database: MinexReports_test
  pool: 5
  username: dj
  password: jordan

production:
  adapter: postgresql
  encoding: unicode
  database: MinexReports_production
  pool: 5
  username: umdjm
  password: M1ch1gan

