
development:
  adapter: postgresql
  encoding: unicode
  database: MinexReports_development
  pool: 5
  username: dj
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: MinexReports_test
  pool: 5
  username: dj
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: MinexReports_production
  pool: 5
  username: umdjm
  password: password
